# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=10)),
                ('thumbnail', models.FilePathField(path=b'./static/shoppingapp/images', recursive=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.Category')),
            ],
        ),
    ]
