# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FilePathField(path=b'C:\\IT\\shoppingsite\\shoppingapp/static/shoppingapp/images/', recursive=True),
        ),
    ]
