# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0002_auto_20161119_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 21, 3, 53, 26, 223186, tzinfo=utc), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FilePathField(path='U:\\shoppingsite\\shoppingapp/static/shoppingapp/images/', recursive=True),
        ),
    ]
