# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_auto_20161121_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='product',
            name='special',
            field=models.FloatField(default=0.0),
        ),
    ]
