# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0006_auto_20161122_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FilePathField(path='U:\\shoppingsite\\shoppingapp/static/shoppingapp/images/', recursive=True),
        ),
    ]
