# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_auto_20161123_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FilePathField(path=b'C:\\IT\\shoppingsite\\shoppingapp/static/shoppingapp/images/', recursive=True),
        ),
    ]
